name: all_action

'on':
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Add a button for manual execution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # More dynamic concurrency group name

jobs:
  UpdateData: # More descriptive job name
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Chrome Version
        run: |
          VERSION_STRING="114.0.5735.106-1"
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CEMS }}
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

#      - name: Check pip cache directory
#        run: pip cache dir

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: c:\users\runneradmin\appdata\local\pip\cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code
        run: |
          python ./code/craw_data.py
        timeout-minutes: 330 # Timeout after nearly 6 hours
        continue-on-error: true

      - name: Commit and push if there are changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "updated" || echo "No changes to commit"
          git pull --rebase origin master
          git push
